# Generated by Django 4.0.4 on 2022-07-21 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='addexpert',
            fields=[
                ('expert_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('expert_name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('dob', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('email', models.CharField(max_length=30)),
                ('photo', models.CharField(max_length=30)),
                ('adhar', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'addexpert',
            },
        ),
        migrations.CreateModel(
            name='tbl_idgen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.IntegerField()),
            ],
            options={
                'db_table': 'tbl_idgen',
            },
        ),
    ]
