# Generated by Django 4.0.4 on 2022-07-25 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentalapp', '0002_rename_addexpert_tbl_expert_alter_tbl_expert_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_expert',
            name='phone',
            field=models.CharField(max_length=100),
        ),
    ]
