# Generated by Django 4.0.4 on 2022-07-26 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentalapp', '0003_alter_tbl_expert_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_expert',
            name='experience',
            field=models.CharField(default='a', max_length=100),
            preserve_default=False,
        ),
    ]
