# Generated by Django 4.0.4 on 2022-07-26 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentalapp', '0004_tbl_expert_experience'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_question',
            fields=[
                ('question_no', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tbl_question',
            },
        ),
        migrations.AddField(
            model_name='tbl_idgen',
            name='qid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
