# Generated by Django 4.0.4 on 2022-07-27 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentalapp', '0006_tbl_login'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tbl_login',
            table='tbl_login',
        ),
        migrations.AlterModelTable(
            name='tbl_question',
            table='tbl_qeustion',
        ),
    ]
