# Generated by Django 4.0.4 on 2022-07-27 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentalapp', '0007_alter_tbl_login_table_alter_tbl_question_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_login',
            old_name='cataegory',
            new_name='category',
        ),
    ]
