# Generated by Django 4.0.4 on 2022-07-27 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentalapp', '0009_tbl_idgen_userid'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_user',
            fields=[
                ('user_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'tbl_user',
            },
        ),
    ]
