# Generated by Django 4.0.4 on 2022-08-01 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentalapp', '0010_tbl_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_expert',
            name='category',
            field=models.CharField(default='a', max_length=100),
            preserve_default=False,
        ),
    ]
