# Generated by Django 4.0.4 on 2022-08-01 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentalapp', '0012_tbl_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_idgen',
            name='article_id',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
