# Generated by Django 4.0.4 on 2022-08-04 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentalapp', '0014_tbl_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_idgen',
            name='video_id',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
