# Generated by Django 4.0.4 on 2022-08-04 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentalapp', '0015_tbl_idgen_video_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_user',
            name='category',
            field=models.CharField(default='a', max_length=100),
            preserve_default=False,
        ),
    ]
