# Generated by Django 4.0.4 on 2022-08-04 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mentalapp', '0016_tbl_user_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_idgen',
            name='query_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='tbl_query',
            fields=[
                ('query_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('date', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('queryanswer', models.CharField(max_length=100)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentalapp.tbl_user')),
            ],
            options={
                'db_table': 'tbl_query',
            },
        ),
    ]
