# Generated by Django 4.0.4 on 2022-08-05 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentalapp', '0017_tbl_idgen_query_id_tbl_query'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_query',
            name='query',
            field=models.CharField(default='a', max_length=100),
            preserve_default=False,
        ),
    ]
