# Generated by Django 4.0.4 on 2022-08-10 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mentalapp', '0019_tbl_idgen_review_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_review',
            fields=[
                ('review_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('reviewdate', models.CharField(max_length=100)),
                ('review', models.CharField(max_length=100)),
                ('expert_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentalapp.tbl_expert')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentalapp.tbl_user')),
            ],
            options={
                'db_table': 'tbl_review',
            },
        ),
    ]
