# Generated by Django 4.0.4 on 2022-08-10 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mentalapp', '0020_tbl_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_idgen',
            name='book_id',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='tbl_bookexpert',
            fields=[
                ('booking_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('bookingdate', models.CharField(max_length=100)),
                ('bookingtime', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('expert_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentalapp.tbl_expert')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentalapp.tbl_user')),
            ],
            options={
                'db_table': 'tbl_book',
            },
        ),
    ]
