# Generated by Django 4.0.4 on 2022-08-10 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentalapp', '0021_tbl_idgen_book_id_tbl_bookexpert'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tbl_bookexpert',
            table='tbl_bookexpert',
        ),
    ]
