# Generated by Django 4.0.4 on 2022-08-11 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mentalapp', '0022_alter_tbl_bookexpert_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_idgen',
            name='webinar_id',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='tbl_webinar',
            fields=[
                ('webinar_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('webinardate', models.CharField(max_length=100)),
                ('Topic', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('expert_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mentalapp.tbl_expert')),
            ],
            options={
                'db_table': 'tbl_webinar',
            },
        ),
    ]
