# Generated by Django 4.0.4 on 2022-08-23 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentalapp', '0026_remove_tbl_result_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_question',
            name='status',
            field=models.CharField(default='q', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='tbl_question',
            table='tbl_question',
        ),
    ]
