# Generated by Django 4.0.4 on 2022-08-24 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentalapp', '0027_tbl_question_status_alter_tbl_question_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_event',
            fields=[
                ('event_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('event', models.CharField(max_length=100)),
                ('photo', models.CharField(max_length=100)),
                ('event_date', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tbl_event',
            },
        ),
        migrations.AddField(
            model_name='tbl_idgen',
            name='event_id',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
